server:
  port: 8880

host:
  local: http://localhost:8080

welcome:
  hello: Welcome to SpringBoot for Xunxiang Wiki

wiki:
  avatar: xxwikiweb/public/images/

#Data Source Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: xunxiangwiki
    url: jdbc:mysql://xunxiangwiki@127.0.0.1/xunxiangwiki?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: xunxiangwiki

redis:
  host: redis-14057.c1.asia-northeast1-1.gce.cloud.redislabs.com
  port: 14057
  password: yzhredis

#Mybatis scan all mapper.xml
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

# 打印所有的sql日志：sql, 参数, 结果
logging:
  level:
    com:
      xunxiang:
        xunxiangwikibase:
          mapper: trace